const MEMBER_AUDIENCE = ["SHOW_FAVORITE", "LOGIN", "SHOW_BOOKS"];
const ADMIN_AUDIENCE = [...MEMBER_AUDIENCE, "ADD_BOOKS", "SHOW_USERS"];

export const JWT_CONFIG = {
  SECRET: process.env.JWT_SECRET,
  ALGORITHM: process.env.JWT_ALGORITHM,
  ISSUER: process.env.JWT_ISSUER,
  EXPIRY: process.env.JWT_EXPIRY,
  MEMBER_AUDIENCE,
  ADMIN_AUDIENCE,
};
